# fly.toml app configuration file generated for insightzuz on 2023-06-07T00:17:24+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "insightzuz"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    start_port = 3000
    end_port = 3000
    handlers = ["http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
